#!/bin/sh

expand_url () {
  base=`extract_base $1`
  path=`extract_path $1`
  user=`extract_user $1`
  url=https://$base/remote.php/dav/files/$user/$path
  echo "$url"
}

extract_base() {
  base=`echo $1 | sed -e 's#\(https\?://\)\?\(.*@\)\?\(.*\)/*:.*#\3#'`
  echo "$base"
}

extract_path() {
  path=`echo $1 | sed -e 's#\(https\?://\)\?.*:/*\(.*\)#\2#'`
  echo "$path"
}

extract_user() {
  user=`echo $1 | sed -e 's#\(https\?://\)\?\(.*@\)\?.*#\2#' | sed -e 's#\(.*\)@#\1#'`
  [ -n "$user" ] || user=$USER
  echo $user
}

probable_file() {
  name=`echo $1 | sed -e 's#.*/##'`
  [ -n "$name" ] || return 1
  echo $name | grep '\.[a-zA-Z0-9]\{1,4\}$' > /dev/null  || return 1
  return 0
}

delete () {
  user=`extract_user $1`
  url=`expand_url $1`

  curl -u $user -X DELETE $url
}

move() {
  user=`extract_user $1`
  src_url=`expand_url $1`
  dest_url=`expand_url $2`

  curl -u $user -X MOVE --header "Destination:$dest_url" $src_url
}

mk_dir() {
  user=`extract_user $1`
  url=`expand_url $1`

  curl -u $user -X MKCOL $url
}

upload() {
  files=$1
  user=`extract_user $2`
  url=`expand_url $2`

  curl -u $user -u $user -T $files $url
}

propget () {
  user=`extract_user $1`
  url=`expand_url $1`

  curl -u $user -X PROPFIND --header "Depth: 1" $url
}

get () {
  user=`extract_user $1`
  url=`expand_url $1`

  curl -u $user -O $url
}

usage() {
  cat  << EOF
Usage: $0 <CMD> <URL>
EOF
exit 1
}

cmd=$1


case "$cmd" in
  put|upload)
    upload $2 $3
    ;;
  mv|move)
    move $2 $3
    ;;
  mkcol|mkdir)
    mk_dir $2
    ;;
  propget|ls|list)
    propget $2
    ;;
  rm|del|delete)
    delete $2
    ;;
  get)
    get $2
    ;;
  *)
   [ -n "$1" ] || usage
   if probable_file $1; then
     get $1
   else
     propget $1
   fi
    ;;
esac
