#!/bin/sh

parse_url () {
  base=`echo $1 | sed -e 's#\(https://\|\)\(.*@\|\)\(.*\)/*:.*#\3#'`
  path=`echo $1 | sed -e 's#\(https://\|\).*:/*\(.*\)#\2#'`
  user=`echo $1 | sed -e 's#\(https://\|\)\(.*@\|\).*#\2#' | sed -e 's#\(.*\)@#\1#'`
  [ -n "$user" ] || user=$USER
  url=https://$base/remote.php/dav/files/$user/$path
  echo "$user#$url"
}

delete () {
  user=`parse_url $1 | cut -d# -f1`
  url=`parse_url $1 | cut -d# -f2`

  curl -u $user -X DELETE $url
}

move() {
  user=`parse_url $1 | cut -d# -f1`
  src_url=`parse_url $1 | cut -d# -f2`
  dest_url=`parse_url $2 | cut -d# -f2`
  curl -u $user -X MOVE --header "Destination:$dest_url" $src_url
}

mk_dir() {
  user=`parse_url $1 | cut -d# -f1`
  url=`parse_url $1 | cut -d# -f2`

  curl -u $user -X MKCOL $url
}

upload() {
  files=$1
  user=`parse_url $2 | cut -d# -f1`
  url=`parse_url $2 | cut -d# -f2`

  curl -u $user -u $user -T $files $url
}

propget () {
  user=`parse_url $1 | cut -d# -f1`
  url=`parse_url $1 | cut -d# -f2`

  curl -u $user -X PROPFIND --header "Depth: 1" $url
}

get () {
  user=`parse_url $1 | cut -d# -f1`
  url=`parse_url $1 | cut -d# -f2`

  curl -u $user $url
}

usage() {
  cat  << EOF
Usage: $0 <CMD> <URL>
EOF
}

cmd=$1


case "$cmd" in
  put|upload)
    upload $2 $3
    ;;
  mv|move)
    move $2 $3
    ;;
  mkdir)
    mk_dir $2
    ;;
  propget)
    propget $2
    ;;
  rm|del|delete)
    delete $2
    ;;
  get)
    get $2
    ;;
  *)
   usage $1
    ;;
esac
